### ISSUE TITLE
集中反馈官网几点问题

### ISSUE THREAD

**Issue by kvkens** [iuap-design/tinper.org#2]
以下问题按照建议来修改即可:
- 首页模块文字显示不一致
  - 直接查看源文件 194 line font嵌套有问题，参考其他模块可看出字体不正确。
- http://tinper.org/favicon.ico  404icon的问题期待补充。
- 页面右下方的`GITHUB`建议修改为`GitHub`。
- 网站ICP备案建议添加工信部链接 http://www.miibeian.gov.cn/

期待越来越好……发现问题会open issue。

**Comment by GuoYongfeng** [comment]
赞。持续内测并改进

**Comment by onvno** [comment]
@kvkens 已处理icon,github,工信部链接问题，3Q

**Comment by onvno** [comment]
最新地址可查看：http://120.27.4.64:8001/

**Comment by kvkens** [comment]
辛苦了，OK了，后面等缓存就好了。
