### ISSUE TITLE
样式板跳转链接有问题

### ISSUE THREAD

**Issue by GuoYongfeng** [iuap-design/tinper.org#24]
### Bug 报告

- __Package version(s)__: (版本号)

#### 描述这个问题:

http://pre.tinper.org/webide/#/demos/ui/dialog

#### 期望的行为:

http:/tinper.org/webide/#/demos/ui/dialog

**Comment by onvno** [comment]
目前查到对应的链接内容非预发布内容，正查找nginx配置问题

**Comment by wangbow** [comment]
问题已解决
