### ISSUE TITLE
neoui的js文档和bee文档混淆了

### ISSUE THREAD

**Issue by GuoYongfeng** [iuap-design/tinper.org#25]
### Bug 报告

- __Package version(s)__: (版本号)

#### 描述这个问题:

请访问`http://tinper.org/dist/neoui/plugin/jsmodal.html`，这里出现了组件库的代码

#### 期望的行为:

组件库文档和neoui文档独立，互不干扰

**Comment by onvno** [comment]
确认为cdn缓存问题，已更新
