### ISSUE TITLE
2016-12-15 上线内容

### ISSUE THREAD

**Issue by GuoYongfeng** [iuap-design/tinper.org#27]
## 2016-12-15 上线内容

**上线 `list` ：**
（示例如下）

- 【Bugfix】修改了某某问题
- 【Feature】新增了某某功能
- 【Update】更新了某某内容

请直接回复issue

**Comment by onvno** [comment]
tinper.org

- 【Bugfix】修正tinper官网webide链接指向

**Comment by whizbz11** [comment]
tinper.org
* 【Update】官网底部
* 【Update】左侧目录

**Comment by HuYuee** [comment]
- 【Bugfix】修改了样式版中的日期控件
- 【Bugfix】修改了grid文档
- 【Feature】新增了neoui链接到polyfill使用说明
