### ISSUE TITLE
neoui 中 tree 的文档不详细

### ISSUE THREAD

**Issue by GuoYongfeng** [iuap-design/tinper.org#29]
# neoui 中 tree 的文档不详细

- 依赖ko，但是文档没有说明，导致使用的时候报错
- 基于z-tree封装，但是文档中没有API说明，也没有链接指向，也不知道一上来如何使用。

**Comment by onvno** [comment]
1.neoui-tree文档demo示例调整，增加ztree示例，增加ztree API链接。
2.问题反馈应该为kero下示例，继续跟进调整

**Comment by onvno** [comment]
kero文档的tree组件调整以下内容：
1.增加指向neoui-tree组件的链接
2.调整依赖文件，增加说明
