### ISSUE TITLE
定制下载页面出现多个undefined

### ISSUE THREAD

**Issue by GuoYongfeng** [iuap-design/tinper.org#30]
### Bug 报告

- __Package version(s)__: (3.1.18)

#### 当前的行为:

定制下载页面出现多个undefined

#### 期望的行为:

正常使用定制功能，undefined的地方正常展示组件选项

**Comment by onvno** [comment]
undefined 为neoui框架新增加了组件未及时提供对应中文组件名称，已提交，在预发布环境目前显示正常
