### ISSUE TITLE
定制后的资源缺少使用指导README文件

### ISSUE THREAD

**Issue by GuoYongfeng** [iuap-design/tinper.org#31]
### Bug 报告

- __Package version(s)__: (3.1.18)

#### 描述这个问题:

定制后的资源缺少使用指导README文件

#### 当前的行为:

定制后的资源缺少使用指导README文件

#### 期望的行为:

定制后的资源需要一个文档告诉用户这里面都包含哪些资源，都是用来干什么的，怎么使用，需要问题怎么需求帮助，拿这些资源如何一步步开发。

**Comment by GuoYongfeng** [comment]
1. 包含哪些资源，用来干嘛
2. 如何使用
3. quickstart

**Comment by onvno** [comment]
定制下载已增加readme提交至develop分支，待部署
