### ISSUE TITLE
tinper官网中用户开发案例描述“...正在使用iup design构建企业级...”是否有误

### ISSUE THREAD

**Issue by vancc** [iuap-design/tinper.org#37]
__用户开发案例__

广大的To B开发者正在使用**iup design**构建企业级应用，我们汇聚部分优秀应用案例展示，供您参考。

**Comment by GuoYongfeng** [comment]
@vancc 感谢反馈。

后续修改成：

> 广大的开发者基于 `tinper` 平台构建企业级应用，我们汇聚部分优秀应用案例供您参考。

**Comment by wangbow** [comment]
done
