### ISSUE TITLE
下拉框控件值显示问题

### ISSUE THREAD

**Issue by zhanghy7** [iuap-design/tinper.org#40]
### Bug 报告
从列表页面进入卡片页面时候，若在数据集绑定时候下拉框的display为none，在数据集绑定完成之后，将其状态设为block的时候其宽度为0，需要显示的数据在数据集中有但是在下拉框中未显示。

- __Package version(s)__: (版本号) u.js 3.1.23

#### 描述这个问题:
通过跟踪代码发现需要修改u.js中的代码，项目中已经验证通过，请平台看看
![image](https://cloud.githubusercontent.com/assets/23067197/23786042/b645b7ae-05a5-11e7-8c7f-0a1075b6c145.png)

**Comment by LiuYueKai** [comment]
已提交
