### ISSUE TITLE
单选按钮问题

### ISSUE THREAD

**Issue by zhanghy7** [iuap-design/tinper.org#41]
### Bug 报告
在项目中发现，单选框非得点两下才能选中，若是一个先选中再选另外一个的话就需要在另一个上点一下后前一个选中消失后才能进行选中。
- __Package version(s)__: (版本号) u.js 3.1.23

#### 描述这个问题:
项目中已经验证通过，请平台看看
![image](https://cloud.githubusercontent.com/assets/23067197/23786293/0c51cb00-05a7-11e7-9692-f914ffd47d16.png)

**Comment by LiuYueKai** [comment]
已提交
