### ISSUE TITLE
首页版本信息不对称

### ISSUE THREAD

**Issue by GuoYongfeng** [iuap-design/tinper.org#5]
### Bug 报告

- __Package version(s)__: (3.1.5)

#### 描述这个问题:

目前官网首页显示最新的是3.1.5版本，但是实际changlog中显示的是3.1.12版本

#### 当前的行为:

目前官网首页显示最新的是3.1.5版本

#### 期望的行为:

首页版本信息更新成正确的版本

**Comment by onvno** [comment]
目前已手动更新3.1.12，后续考虑自动方案

**Comment by onvno** [comment]
此问题会同合并到历史版本下载issue中，关闭
