### ISSUE TITLE
历史版本页面下载提示不明显

### ISSUE THREAD

**Issue by GuoYongfeng** [iuap-design/tinper.org#6]
### Bug 报告

- __Package version(s)__: (3.1.5)

#### 描述这个问题:

我从首页上点击历史版本进入版本下载页面，但是不知道版本号就是可下载的按钮

#### 当前的行为:

需要点击版本号才能进行版本资源下载

#### 期望的行为:

每个版本下面有对应的下载按钮可以直接点击下载

**Comment by onvno** [comment]
已调整页面并在最新页面做更改
