### ISSUE TITLE
首页下载应该下拉展示版本下载和定制下载两个内容

### ISSUE THREAD

**Issue by GuoYongfeng** [iuap-design/tinper.org#7]
### Bug 报告

- __Package version(s)__: (3.1.5)

#### 描述这个问题:

历史版本下载只能从官网首页一个很不显眼的入口进去，而导航处的下载进去只有定制下载的功能，无法完全覆盖用户需求。

#### 当前的行为:

网站导航的下载栏点击进去就是定制下载

#### 期望的行为:

希望导航的下载栏是个用户可选的下拉，放置版本下载和定制下载两个功能。

**Comment by onvno** [comment]
最新develop分支已更新。
